spring.application.name=study
server.port=9090

# Database connection URL (default port for PostgreSQL is 5432)
spring.datasource.user.jdbc-url=jdbc:postgresql://localhost:5434/user_db
spring.datasource.user.username=admin
spring.datasource.user.password=password123

spring.datasource.product.jdbc-url=jdbc:postgresql://localhost:5434/product_db
spring.datasource.product.username=admin
spring.datasource.product.password=password123

# Configure JPA/Hibernate properties
# 'update' automatically updates the database schema based on your entities
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100

#Flyway
# B\u1EADt/T\u1EAFt Flyway (true l\u00E0 cho ph\u00E9p t\u1EF1 \u0111\u1ED9ng ch\u1EA1y migration khi start app)
spring.flyway.enabled=false
#spring.flyway.placeholders.schemaName=my_schema

# Ch\u1EBF \u0111\u1ED9 Baseline:
# false (M\u1EB7c \u0111\u1ECBnh): S\u1EBD b\u00E1o l\u1ED7i n\u1EBFu DB \u0111\u00E3 c\u00F3 d\u1EEF li\u1EC7u m\u00E0 ch\u01B0a c\u00F3 b\u1EA3ng l\u1ECBch s\u1EED Flyway.
# true: S\u1EBD t\u1EF1 t\u1EA1o b\u1EA3ng l\u1ECBch s\u1EED v\u00E0 coi DB hi\u1EC7n t\u1EA1i l\u00E0 phi\u00EAn b\u1EA3n g\u1ED1c (v1) n\u1EBFu g\u1EB7p DB c\u0169.
#spring.flyway.baseline-on-migrate=true
#spring.flyway.baseline-version=0

# \u0110\u01B0\u1EDDng d\u1EABn t\u1EDBi th\u01B0 m\u1EE5c ch\u1EE9a c\u00E1c file SQL migration
# C\u00E1c file th\u01B0\u1EDDng \u0111\u1EB7t trong: src/main/resources/db/migration
#spring.flyway.locations=classpath:db/migration